"use client";

import { useState } from "react";
import { ExternalLink, Play, Image, FileCode, Copy, Check, Info } from "lucide-react";
import type { Creative, CreativePerformanceSummary } from "@/types/api";
import { cn, getFormatColor, getFormatLabel, getStatusColor } from "@/lib/utils";
import { getGoogleAuthBuyersUrl, extractBuyerIdFromName } from "@/lib/url-utils";

interface CreativeCardProps {
  creative: Creative;
  onPreview?: (creative: Creative) => void;
  performance?: CreativePerformanceSummary;
  sortField?: "spend" | "impressions" | "clicks" | "ctr" | null;
}

// Format spend in micros to compact USD string
function formatSpend(microDollars: number | null | undefined): string {
  if (!microDollars) return "$0";
  const dollars = microDollars / 1_000_000;
  if (dollars >= 1000) return `$${(dollars / 1000).toFixed(1)}K`;
  if (dollars >= 1) return `$${dollars.toFixed(0)}`;
  return `$${dollars.toFixed(2)}`;
}

// Format large numbers compactly
function formatNumber(n: number | null | undefined): string {
  if (!n) return "0";
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

// Format CTR percentage
function formatCTR(ctr: number | null | undefined): string {
  if (ctr === null || ctr === undefined) return "-";
  return `${ctr.toFixed(2)}%`;
}

function PreviewThumbnail({ creative }: { creative: Creative }) {
  // For VIDEO: show thumbnail if available, otherwise gradient placeholder
  if (creative.format === "VIDEO") {
    const thumbnailUrl = creative.video?.thumbnail_url;

    return (
      <div className="relative h-24 bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center overflow-hidden group/thumb">
        {thumbnailUrl ? (
          <>
            <img
              src={thumbnailUrl}
              alt="Video thumbnail"
              className="w-full h-full object-cover"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
            <div className="absolute inset-0 bg-black/30 flex items-center justify-center">
              <div className="w-10 h-10 rounded-full bg-black/50 flex items-center justify-center">
                <Play className="h-5 w-5 text-white ml-0.5" fill="currentColor" />
              </div>
            </div>
            {/* Info badge - shows on hover to explain thumbnail is auto-generated */}
            <div className="absolute top-1 left-1 opacity-0 group-hover/thumb:opacity-100 transition-opacity">
              <div className="relative group/info">
                <div className="flex items-center gap-1 px-1.5 py-0.5 bg-black/70 rounded text-[10px] text-gray-300">
                  <Info className="h-3 w-3" />
                  Preview
                </div>
                <div className="hidden group-hover/info:block absolute top-6 left-0 w-48 p-2 bg-gray-900 border border-gray-700 rounded-lg text-xs text-gray-300 shadow-lg z-20">
                  <p className="font-medium mb-1">Auto-generated preview</p>
                  <p className="text-gray-400">
                    Generated by Cat-Scan for internal reference. Not visible to end users.
                  </p>
                </div>
              </div>
            </div>
          </>
        ) : (
          <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center">
            <Play className="h-5 w-5 text-white ml-0.5" fill="currentColor" />
          </div>
        )}
        {creative.video?.duration && (
          <span className="absolute bottom-1 right-1 bg-black/70 text-white text-[10px] px-1 py-0.5 rounded">
            {creative.video.duration}
          </span>
        )}
      </div>
    );
  }

  // For NATIVE: prefer logo/icon, fall back to main image
  if (creative.format === "NATIVE") {
    const imageUrl = creative.native?.logo?.url || creative.native?.image?.url;
    return (
      <div className="relative h-24 bg-gradient-to-br from-green-50 to-green-100 flex items-center justify-center overflow-hidden">
        {imageUrl ? (
          <img
            src={imageUrl}
            alt={creative.native?.headline || "Native ad"}
            className="w-full h-full object-cover"
            onError={(e) => {
              (e.target as HTMLImageElement).style.display = "none";
            }}
          />
        ) : (
          <Image className="h-8 w-8 text-green-400" />
        )}
      </div>
    );
  }

  // For HTML/Display: show code icon placeholder
  if (creative.format === "HTML") {
    return (
      <div className="relative h-24 bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center">
        <FileCode className="h-8 w-8 text-blue-400" />
      </div>
    );
  }

  // For IMAGE/Display: show image icon placeholder (same styling as HTML)
  if (creative.format === "IMAGE") {
    return (
      <div className="relative h-24 bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center">
        <Image className="h-8 w-8 text-blue-400" />
      </div>
    );
  }

  // Default placeholder for unknown formats
  return (
    <div className="h-24 bg-gray-100 flex items-center justify-center text-gray-400">
      <Image className="h-8 w-8" />
    </div>
  );
}

export function CreativeCard({ creative, onPreview, performance, sortField }: CreativeCardProps) {
  const [copied, setCopied] = useState(false);
  const hasPreview = creative.video || creative.html || creative.native;
  const hasData = performance?.has_data;

  // Get Google Console URL
  const buyerId = creative.buyer_id || extractBuyerIdFromName(creative.name);
  const googleUrl = buyerId ? getGoogleAuthBuyersUrl(buyerId, creative.id) : null;

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation();
    await navigator.clipboard.writeText(creative.id);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  // Determine if we should show spend first (when sorted by spend)
  const showSpendFirst = sortField === "spend";

  return (
    <div className="card overflow-hidden hover:shadow-md transition-shadow">
      {/* Thumbnail */}
      <div
        className={cn("cursor-pointer", hasPreview && "hover:opacity-90")}
        onClick={() => hasPreview && onPreview?.(creative)}
      >
        <PreviewThumbnail creative={creative} />
      </div>

      <div className="p-3">
        {/* Header: ID + Spend (order depends on sort) */}
        <div className="flex items-center justify-between gap-2">
          <div className="flex-1 min-w-0">
            {showSpendFirst ? (
              <>
                {/* Spend first when sorted by spend */}
                <div className="text-base font-medium text-gray-900">
                  {hasData ? `${formatSpend(performance?.total_spend_micros)} spent` : "No data"}
                </div>
                <div className="text-sm text-gray-500 font-mono truncate" title={creative.id}>
                  #{creative.id}
                </div>
              </>
            ) : (
              <>
                {/* ID first (default) */}
                <div className="text-sm font-medium text-gray-900 font-mono truncate" title={creative.id}>
                  #{creative.id}
                </div>
                <div className={cn(
                  "text-base font-medium",
                  hasData ? "text-gray-900" : "text-gray-400"
                )}>
                  {hasData ? `${formatSpend(performance?.total_spend_micros)} spent` : "No performance data"}
                </div>
              </>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-1 flex-shrink-0">
            <button
              onClick={handleCopy}
              className="p-1 text-gray-400 hover:text-gray-600 rounded"
              title="Copy ID"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
            </button>
            {googleUrl && (
              <a
                href={googleUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="p-1 text-gray-400 hover:text-primary-600 rounded"
                title="View in Google Console"
                onClick={(e) => e.stopPropagation()}
              >
                <ExternalLink className="h-3.5 w-3.5" />
              </a>
            )}
          </div>
        </div>

        {/* Metrics row - only show if has data */}
        {hasData && (
          <div className="mt-2 text-xs text-gray-500">
            {formatNumber(performance?.total_impressions)} imps · {formatCTR(performance?.ctr_percent)} CTR
          </div>
        )}

        {/* Badges: Format + Status only */}
        <div className="mt-2 flex flex-wrap gap-1.5">
          <span className={cn("badge text-[10px] px-1.5 py-0.5", getFormatColor(creative.format))}>
            {getFormatLabel(creative.format)}
          </span>
          {creative.approval_status && (
            <span className={cn("badge text-[10px] px-1.5 py-0.5", getStatusColor(creative.approval_status))}>
              {creative.approval_status === "APPROVED" ? "✓" : ""} {creative.approval_status.replace("_", " ")}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
